name: chewie_media_kit
description: Chewie controls for media_kit
version: 1.8.1
homepage: https://github.com/GlitterWare/chewie_media_kit

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  media_kit: ^1.0.0
  media_kit_video: ^1.2.4
  wakelock_plus: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
